Task/restructure workflow
tektronix/tsp-toolkit-webhelp-to-json pull request #1
Opened 2024-04-08 06:35 UTC by jharajeev55

2024-04-09 12:51 UTC, esarver commented on .github/workflows/pr.yml
> +    runs-on: windows-latest
Does this need to be on windows? It seems like it should be able to run on `ubuntu-latest`. Windows runners use 2x the CI minutes of Linux runners.

2024-04-10 11:58 UTC, jharajeev55 commented on ParserGeneric/HelperFunctions.py
> +    file_path = os.path.join("ParserGeneric","tti-command_param_data_type.txt")
ticket has been created.

2024-04-10 12:00 UTC, esarver requested changes

2024-04-10 12:00 UTC, esarver commented on CHANGELOG.md
> +- workflow has been added for generaing josn artificts.
```suggestion
- workflow has been added for generaing json artifacts.
```

2024-04-10 12:02 UTC, esarver approved these changes

2024-04-10 12:19 UTC, merged